baseURL: https://dhruvpeter.github.io/blogs.core.ai/
languageCode: en-us
title: core.ai tech blogs
theme: "PaperMod"
publishDir: "docs"
paginate: 5 # Maximum number of blogs displayed as list

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Categories
      url: categories/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params: # Give default parameters
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author:
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true # Table of Contents
  TocOpen: false
  # comments: false
  images: [""]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams: # Home page details
    Title: "core.ai tech blogs"
    Content: >
      Welcome to core.ai tech blogs.
  socialIcons:
    - name: github
      url: "https://github.com/aicore/blogs.core.ai"
    - name: twitter
      url: "https://twitter.com/core_ai_scien"
    - name: linkedin
      url: "https://www.linkedin.com/company/core-ai-scientific/?originalSubdomain=in"
    - name: discord
      url: "https://discord.gg/GaBDAK7BRM"

  editPost: # Button to edit content. On clicling it will redirect to git repo
    URL: "https://github.com/aicore/blogs.core.ai/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts: # Configuration for search
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
